name: Docker Image CI/CD
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: test
        run: env
      - name: Build image
        run: docker build . --file Dockerfile -t ${{ secrets.DOCKER_REPOSITORY }}:amd64-${{ github.ref }}-${GITHUB_SHA::8}
      - name: Build arm64 image
        run: docker build . --file Dockerfile.arm64 -t ${{ secrets.DOCKER_REPOSITORY }}:arm64-${{ github.ref }}-${GITHUB_SHA::8}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_REPOSITORY }}:amd64-${{ github.ref }}-${GITHUB_SHA::8}
            ${{ secrets.DOCKER_REPOSITORY }}:arm64-${{ github.ref }}-${GITHUB_SHA::8}
